server:
  port: 9000

spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#Springboot整合dubbo  
dubbo:
  scan:
    basePackages: com.github.gudian1618.dubbo.jt #包扫描dubbo的service注解
  application:
    name: provider-user  #提供者服务名称
  registry:              #链接zookeeper
    address: zookeeper://127.0.0.1:2182?backup=127.0.0.1:2181,127.0.0.1:2183
  #  configcenter: zookeeper://127.0.0.1:2182
  metadata-report:
    address: zookeeper://127.0.0.1:2182
  protocol:
    name: dubbo 
    port: 20880   #服务通信端口 消费者链接提供者端口

      
mybatis-plus:
  type-aliases-package: com.github.gudian1618.dubbo.jt.pojo       #配置别名包路径
  mapper-locations: classpath:/mybatis/mappers/*.xml  #添加mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                #开启驼峰映射规则